#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse
#
script_update=2020.07.15
script_version=r10005
################################################################################################
action=$1
iUser=$2
if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function
else
    source <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/function)
fi
export_inexistence_info
check_var_iUser_iPass_iHome
################################################################################################
app_script=ffgg
app=FlexGet
app_systemd=flexget
app_command=flexget
app_config=$iHome/.config/flexget/config.yml
app_log=$iHome/.config/flexget/flexget.log
app_webui_port=$(grep "web_server" -A7 $app_config | grep -i port | grep -oE "[0-9]+")
# app_version=$($app_command -V 2>/dev/null | head -1 | grep -oE "[0-9.]+") # check version is too slow, so only check it when needed
[[ -n $serveripv4 ]] && app_web_url="Web          http://${serveripv4}:${app_webui_port}"
################################################################################################

show_usage() {

echo -e "Usage: $app_script [action] [username]

Action:
a            Start   ${app}
b            Stop    ${app}
c            Check   ${app} status
l            View    ${app}'s log
r            Restart ${app}
s            Edit    ${app}'s configuration file
x            Enable  ${app}'s auto-start after reboot
y            Disable ${app}'s auto-start after reboot

$app_script         $script_version ($script_update)
User         $iUser
Version      $app $($app_command -V 2>/dev/null | head -1 | grep -oE "[0-9.]+")
Config       $app_config
Logfile      $app_log
Plugin       $iHome/.config/flexget/plugins
WebUI Port   $app_webui_port
$app_web_url
"
exit 0
}

[[ -z $action ]] && show_usage

case $action in
    a ) systemctl start   $app_systemd@$iUser ;;
    b ) systemctl stop    $app_systemd@$iUser ;;
    c ) systemctl status  $app_systemd@$iUser ;;
    r ) systemctl restart $app_systemd@$iUser ;;
    x ) systemctl enable  $app_systemd@$iUser ;;
    y ) systemctl disable $app_systemd@$iUser ;;
    h ) show_usage                            ;;
    l ) tail -300 $app_log                    ;;
    s ) nano +40  $app_config                 ;;
    * ) echo -e "ERROR: Unknown action $action" ; show_usage ;;
esac
