#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse

script_update=2020.04.11
script_version=r10001

################################################################################################ Debug

usage_for_debug() {
    export local_packages=/etc/inexistence/00.Installation
    export s=$local_packages/package/filebrowser
    rm -f $s ; nano $s
    if [[ -f /etc/inexistence/00.Installation/package/filebrowser ]]; then
        bash /etc/inexistence/00.Installation/package/filebrowser
    else
        bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/package/filebrowser)
    fi
}

################################################################################################

unset LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG

AppName=FileBrowser
AppNameLower=filebrowser
AppExec=""
AppTest="docker ps | grep -q filebrowser"
Need_SourceCode=no
pm_action=install

function show_usage() { echo "
$AppName $pm_action $script_version ($script_update)
Usage:
      -l        Specifiy LogBase (Not log file)
      -d        Enable debug mode
      -w        WebUI port for FileBrowser
      --log     Show logfile's content"
exit 1 ; }

OPTS=$(getopt -o v:l:w:d -al version:,debug,logbase:,wport:,log -- "$@")
[ ! $? = 0 ] && show_usage
eval set -- "$OPTS"

while [ -n "$1" ] ; do case "$1" in
    -v | --version      ) version="$2"  ; shift 2 ;;
    -l | --logbase      ) LogTimes="$2" ; shift 2 ;;
    -d | --debug        ) debug=1       ; shift   ;;
    -w | --wport    ) wPort="$2"    ; shift 2 ;;
         --log          ) show_log=1    ; shift   ;;
    -- ) shift ; break ;;
esac ; done

################################################################################################ Set Variables

if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function
else
    source <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/function)
fi

set_variables_log_location
check_var_OutputLOG
debug_log_location
cat_outputlog
[[ -z $wport ]] && wport=7575
PortCheck $wport
[[ $port_used == 1 ]] && echo_error_exit "Please change your port"

################################################################################################

function install_filebrowser () {
    mkdir -p $HOME/.docker/fb/myfiles
    docker run -itd  \
            -e PUID=$UID \
            -e PGID=$GID \
            -e WEB_PORT=$wport \
            -e FB_AUTH_SERVER_ADDR="127.0.0.1" \
            -p $wport:$wport \
            -v $HOME/.docker/fb/config:/config \
            -v /:/myfiles \
            --mount type=tmpfs,destination=/tmp \
            --restart always \
            80x86/filebrowser:amd64 >> "$OutputLOG" 2>&1
    generate_status_lock
}

################################################################################################

install_base docker
which docker > /dev/null || echo_error_exit "No Docker found"
echo_task "Installing $AppName ..."
install_filebrowser & spinner $!
check_status $AppNameLower
