#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse

script_update=2020.06.02
script_version=r11008

################################################################################################ Debug

usage_for_debug() {
    bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/hezi)
    s=/etc/inexistence/00.Installation/hezi;rm -f $s ; nano $s ; chmod 755 $s
}

################################################################################################ Set Variables 1

if [[ -d /etc/inexistence/00.Installation ]]; then
    source /etc/inexistence/00.Installation/function
    source /etc/inexistence/00.Installation/ask
else
    source <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/function)
    source <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/ask)
fi

################################################################################################ Set Variables 2

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$PATH
export TZ=/usr/share/zoneinfo/Asia/Shanghai
export DEBIAN_FRONTEND=noninteractive
export APT_LISTCHANGES_FRONTEND=none
export local_packages=/etc/inexistence/00.Installation
export local_script=/usr/local/bin/abox

export iBranch=master
export times=0
export LogBase=/log/inexistence
export LogTimes=$LogBase/$times
export SourceLocation=$LogTimes/source
export DebLocation=$LogTimes/deb
export LogLocation=$LogTimes/install
export LOCKLocation=$LogBase/.lock
export WebROOT=/var/www

export MAXCPUS=$(nproc)
export script_lang=chs
export just_upgrade=1
export_inexistence_info

################################################################################################

function possible_usage () {
    hezi anzhuang rclone wine mono
    hezi anzhuang deluge
    # 可以是输入 hezi 后，出现类似 acctcp 脚本的一个选单，或者直接用 whiptail 来做
}

################################################################################################

set_language
check_install_2
get_clients_version
mkdir -p $LogBase/$times

if [[ -z $iPass ]]; then
    create_user=1
    ask_username
    ask_password
fi

# password needed
# [[ -n $qb_installed_ver ]] && 
ask_qbittorrent
# [[ -n $de_installed_ver ]] && 
ask_deluge
# [[ -n $tr_installed_ver ]] && 
ask_transmission
ask_rtorrent
ask_flexget
ask_filebrowser
ask_rdp
# password not needed
ask_wine
ask_mono
ask_rclone
ask_tools

if_need_lt=0
[[ $qb_version != No ]] && [[ -z $qb_mode ]] && if_need_lt=1
[[ $de_version != No ]] && if_need_lt=1
[[ $if_need_lt == 1 ]] && [[ -z $lt_version ]] && lt_version=RC_1_1

if [[ $create_user == 1 ]]; then
    hezi_add_user $iUser $iPass
fi

do_installation
