#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse
#
# script_update=2020.06.02
# script_version=r10003
# This var will recover other script's var when source
#
################################################################################################

function show_inex_usage () {
    echo -e "
$script_name $script_version ($script_update)

Usage: $script_cmd [OPTS]

Options:
  -u, --username <username>       Specify username
  -p. --password <password>       Specify password
  --qb <qb_version|no>            Specify which qBittorrent version to be installed
  --de <de_version|no>            Specify which Deluge version to be installed
  --rt <rt_version|no>            Specify which rTorrent version to be installed
  --tr <tr_version|no>            Specify which Transmission version to be installed
  --domain <your_domain>          Configure SSL for you domain via acme.sh
  --hostname  <hostname>          Setup hostname (make no change by default)
  --mt-<single|double|half|max>   How many threads will be used when compiling from source (default all)
  -b <branch>                     Specify which branch of inexistence to be installed (default master)
  -d, --debug                     Enable debug mode
  -s, --skip                      Skip system check
  -y, --yes                       Force yes to all questions
  --enable-ipv6                   Enable IPv6 for rTorrent
  --qb-static                     Install qBittorrent static builds instead of via deb or compile
  --tr-deb                        Install Transmission 2.94 via deb
  -h, --help                      Display this help and exit

  --APPNAME                       Install an application

  Available APPNAME:
  vnc | x2go | wine | mono | tools | rclone | flood | flexget | filebrowser | bbr | tweaks | swap

  --no-SOMETHING                  DO NOT install or do something

  Available SOMETHING:
  flexget | filebrowser | bbr | tweaks | swap | reboot | system-upgrade | source-change

Example:
  $script_cmd -u aniverse -p ajYeTGRkFw42 -y --de 1.3.15 --qb no --rt no  \\
  --hostname myseedbox --flexget --no-bbr --rclone --tweaks --tr-deb --vnc \\
  --no-system-upgrade --no-reboot --no-source-change --no-filebrowser
"
    exit
}

################################################################################################

function opts_action () {
    while [ -n "$1" ] ; do case "$1" in
        -u | --user       ) iUser=$2          ; shift 2 ;;
        -p | --password   ) iPass=$2          ; shift 2 ;;
        -b | --branch     ) iBranch=$2        ; shift 2 ;;
    
        --de              ) de_version=$2     ; shift 2 ;;
        --qb              ) qb_version=$2     ; shift 2 ;;
        --tr              ) tr_version=$2     ; shift 2 ;;
        --rt              ) rt_version=$2     ; shift 2 ;;
        --lt              ) lt_version=$2     ; shift 2 ;;
        --domain          ) rt_domain=$2      ; shift 2 ;;
        --hostname        ) hostname=$2       ; shift 2 ;;
    
        -d | --debug      ) DeBUG=1           ; shift ;;
        -s | --skip       ) SYSTEMCHECK=0     ; shift ;;
        -y | --yes        ) ForceYes=1        ; shift ;;
        -h | --help       ) show_inex_usage   ; shift ;;
        --separate        ) separate=1        ; shift ;;
        --quick           ) quick=1           ; shift ;;
        --qb-static       ) qb_mode=static    ; shift ;;
        --sihuo           ) sihuo=yes         ; shift ;;
        --eng             ) script_lang=eng   ; shift ;;
        --chs             ) script_lang=chs   ; shift ;;
        --enable-ipv6     ) IPv6Opt=-i        ; shift ;;
    
        --vnc             ) InsVNC="Yes"      ; shift ;;
        --x2go            ) InsX2Go="Yes"     ; shift ;;
        --wine            ) InsWine="Yes"     ; shift ;;
        --mono            ) InsMono="Yes"     ; shift ;;
        --tools           ) InsTools="Yes"    ; shift ;;
        --rclone          ) InsRclone="Yes"   ; shift ;;
        --flood           ) InsFlood="Yes"    ; shift ;;
    
        --swap            ) USESWAP="Yes"     ; shift ;;
        --filebrowser     ) InsFB="Yes"       ; shift ;;
        --flexget         ) InsFlex="Yes"     ; shift ;;
        --tweaks          ) UseTweaks="Yes"   ; shift ;;
        --bbr             ) InsBBR="Yes"      ; shift ;;
    
        --no-swap         ) USESWAP="No"      ; shift ;;
        --no-filebrowser  ) InsFB="No"        ; shift ;;
        --no-flexget      ) InsFlex="No"      ; shift ;;
        --no-tweaks       ) UseTweaks="No"    ; shift ;;
        --no-bbr          ) InsBBR="No"       ; shift ;;
        --no-source-change) aptsources="No"   ; shift ;;
    
        --no-reboot       ) NoReboot=1        ; shift ;;
        --mt-single       ) MAXCPUS=1         ; shift ;;
        --mt-double       ) MAXCPUS=2         ; shift ;;
        --mt-all          ) MAXCPUS=$(nproc)  ; shift ;;
        --mt-half         ) MAXCPUS=$(echo "$(nproc) / 2"|bc)   ; shift ;;
        --tr-deb          ) tr_version=2.94   ; TRdefault=deb   ; shift ;;
        --no-system-upgrade ) skip_system_upgrade=1             ; shift ;;
    
        -- ) shift ; break ;;
    esac ; done
}
    