#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse

script_update=2019.07.10
script_version=r10001

################################################################################################ Get options

function show_usage() { echo " Invalid option $1"
exit 1 ; }

OPTS=$(getopt -o v: -al debug,version:,logbase: -- "$@")
[ ! $? = 0 ] && show_usage
eval set -- "$OPTS"

while [ -n "$1" ] ; do case "$1" in
         --logbase      ) LogTimes="$2" ; shift 2 ;;
         --debug        ) debug=1       ; shift   ;;
         --             ) shift ; break ;;
esac ; done

LogRootPath=/log/inexistence
[[ -z $LogTimes ]] && LogTimes=$LogRootPath/single
OutputLOG=$LogTimes/uninstall/rclone.txt    # /dev/null
LOCKLocation=$LogRootPath/lock

if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function --output $OutputLOG
else
    wget -qO /tmp/function https://github.com/Aniverse/inexistence/raw/master/00.Installation/function
    source /tmp/function --output $OutputLOG
fi

################################################################################################

mkdir -p $LOCKLocation $LogTimes/uninstall
echo "\n\n\n$(date "+%Y.%m.%d.%H.%M.%S")\n\n\n" >> $OutputLOG

function uninstall_rclone() {
    rm -f /usr/bin/rclone /usr/local/share/man/man1/rclone.1 $LOCKLocation/rclone.lock
    mandb >> $OutputLOG 2>&1

    status_lock=rclone-r
    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock 
    [[ ! -x /usr/bin/rclone ]] && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
    echo >> $OutputLOG
}




echo -ne "Uninstalling rclone ..." | tee -a $OutputLOG
uninstall_rclone & spinner $!
check_status $status_lock | tee -a $OutputLOG
