#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse
#
script_update=2019.07.10
script_version=r10002
################################################################################################
action=$1
iUser=$2
DefaultUser=$(cat /log/inexistence/iUser.txt 2>/dev/null | head -1)
[[ -z $DefaultUser ]] && DefaultUserDisplay="Error: No default user found" || DefaultUserDisplay="Default user: $DefaultUser"
[[ -z $iUser  ]] && iUser=$DefaultUser
id -u "$iUser" >/dev/null 2>&1 || { echo -e "No invalid user input" ; exit 1 ; }
################################################################################################
[[ $iUser == root ]] && iHome=/root
[[ $iUser != root ]] && iHome=/home/$iUser
app=qBittorrent
app_systemd=qbittorrent
app_command=qbittorrent-nox
app_config=$iHome/.config/qBittorrent/qBittorrent.conf
app_log=$iHome/.config/qBittorrent/qbittorrent.log
################################################################################################

show_usage() {

echo -e "Usage: qb [action] [username]

Action:
a      Start   $app
b      Stop    $app
c      Check   $app status
l      View    ${app}'s log
r      Restart $app
s      Edit    ${app}'s configuration file
x      Enable  ${app}'s auto-start after reboot
y      Disable ${app}'s auto-start after reboot

$DefaultUserDisplay
"
exit 0
}

[[ -z $action ]] && show_usage

case $action in
    a ) systemctl start   $app_systemd@$iUser ;;
    b ) systemctl stop    $app_systemd@$iUser ;;
    c ) systemctl status  $app_systemd@$iUser ;;
    r ) systemctl restart $app_systemd@$iUser ;;
    x ) systemctl enable  $app_systemd@$iUser ;;
    y ) systemctl disable $app_systemd@$iUser ;;
    l ) tail -300 $app_log    ;;
    s ) nano +40  $app_config ;;
    * ) echo -e "ERROR: Unknown action" ; show_usage ;;
esac
