#!/bin/bash
# https://www.reddit.com/r/seedboxes/comments/6qhuig/deluge_is_better_at_the_initial_downloads/
# https://github.com/wseedbox/deluge-to-rtorrent
# Thanks to the original author: woodsdog
# MOdified by Aniverse

# 
if [[ -z "${SKIP_SLEEP+x}" ]]; then
  sleep 900
fi

torrentid=$1
torrentname=$2
torrentpath=$3

tmpdir=$(mktemp -d)

##############################################################
# Define these vars to the path where they are located
##############################################################
dc=/usr/bin/deluge-console
deluge_state_dir=/root/.config/deluge/state
rtfr=/usr/local/bin/rtnew
torrent_download_dir=/home/ANUSER/deluge/download
rtxmlrpc=/usr/local/bin/rtxmlrpc
xmlrpc_endpoint=127.0.0.1
xmlrpc_command="${rtxmlrpc} ${xmlrpc_endpoint}"
##############################################################

function on_exit() {
    rm -rf "${tmpdir}"
}

#trap on_exit EXIT

tracker_line=$($dc info $torrentid | grep "^Tracker" | awk -F: '{print $2}' | tr -d " ")
set_tracker $tracker_line
ratio=$($dc info $torrentid | grep Ratio: | awk -F "Ratio: " '{print $2}')

#echo $tracker
#echo $ratio

cp ${deluge_state_dir}/${torrentid}.torrent ${tmpdir}

$rtfr $torrent_download_dir ${deluge_state_dir}/${torrentid}.torrent ${tmpdir}/${torrentid}_fast.torrent
if [[ $? -ne 0 ]]; then
  echo "Something went wrong when converting the torrent file with $(basename ${torrent_download_dir})"
  echo "exiting..."
  exit 10
fi

# remove the torrent from deluge
$dc rm $torrentid

$rtxmlrpc load.start ${tmpdir}/${torrentid}_fast.torrent
sleep 3
$rtxmlrpc d.set_custom ${torrentid} deluge_ratio ${ratio}

/usr/bin/rm -rf $tmpdir
