#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse
#
#################################################################################

script_update=2020.01.25
script_version=r20005

#################################################################################

usage_guide() {
s=/usr/bin/deluge-update-tracker
s=/root/deluge-update-tracker
rm -f $s ; nano $s ; chmod 755 $s
# enable execute plugin, reboot deluged, use /root/deluge-update-tracker as path (/usr/bin/deluge-update-tracker or deluge-update-tracker is not executeable emmmm)
}

#################################################################################

torrentid=$1
torrentname=$2
torrentpath=$3

#################################################################################

black='\033[0;30m'   ; red='\033[0;31m'     ; green='\033[0;32m'   ; yellow='\033[0;33m' ;  bold='\033[1m'
blue='\033[0;34m'    ; magenta='\033[0;35m' ; cyan='\033[0;36m'    ; white='\033[0;37m'  ;  normal='\033[0m'

#################################################################################

local=127.0.0.1
log=/log/script/deluge-update-tracker.log
[[ ! -f $log ]] && { mkdir -p $(dirname $log) ; touch $log ; }

# ddport=58846
ddport=$(grep '"daemon_port": [0-9]*' $HOME/.config/deluge/core.conf | grep -oE "[0-9]+")
[[ -z $ddport ]] && { echo "ERROR: No daemon port detected!" >> $log ; exit 1 ; }
[[ -z $(which deluge-console) ]] && { echo "ERROR: No deluge-console detected!" >> $log ; exit 1 ; }

#################################################################################

function clean_history(){ echo -n > $log ; }
function tail_log(){      tail -300 $log ; }

#################################################################################

OPTS=$(getopt -n "$0" -o cl --long "log,clean" -- "$@")
#[ ! $? = 0 ] && show_usage
eval set -- "$OPTS"

while [ -n "$1" ] ; do case "$1" in
    -l | --log   ) tail_log        ; NoAction=y ; shift ;;
    -c | --clean ) clean_history   ; NoAction=y ; shift ;;
    -- ) shift ; break ;;
esac ; done

#################################################################################
[[ $NoAction != y ]] && { x=1





while [ $x -le 65 ]; do
    sleep 2
    echo -e "$(date "+%Y.%m.%d %H:%M:%S") [$x]\t$torrentname" >> $log
    line=$(deluge-console "connect $local:$ddport; info" $1 2>1 | grep "Tracker status")
    echo "$line" >> $log
    case "$line" in
		*Unregistered*|*unregistered*|*Sent*|*End*of*file*|*Bad*Gateway*|*Error*|*timed*out)
            deluge-console "connect $local:$ddport; pause '$torrentid'"
            sleep 2
            deluge-console "connect $local:$ddport; resume '$torrentid'"
            ;;
        *)
            echo -e "${green}[Good] $torrentname${normal}\n" >> $log
            break ;;
    esac
    x=$(( $x + 1 ))
done





}
#################################################################################
#################################################################################
#################################################################################
#################################################################################
#################################################################################



unused_codes_ignore_these() {
# echo "[Info]    TorrentID: $torrentid" >> $log
# echo "${blue}[Info]    TorrentName: $torrentname${normal}" >> $log
    Usernamee=ANUSER
    Passwordd=ANPASS
    line=$(/usr/bin/deluge-console "connect 127.0.0.1:$ddport $Usernamee $Passwordd; info" $1 | grep "Tracker status")
    echo $line >> $log
    case "$line" in
        *unregistered*|*Sent*|*End*of*file*|*Bad*Gateway*) eval /usr/bin/deluge-console "connect 127.0.0.1:$ddport $Usernamee $Passwordd\; update-tracker '$torrentid'";;
        *) echo "Found working torrent: $torrentname $torrentpath $torrentid" >> ~/script.log ; exit 1 ;;
    esac
}