#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse
#
# 2018.11.17
# 1.01

OutputLOG=/etc/inexistence/01.Log/install_rclone.txt # /dev/null
LOCKLocation=/etc/inexistence/01.Log/Lock
SCLocation=/etc/inexistence/01.Log/SourceCodes

mkdir -p $LOCKLocation
echo "\n\n\n$(date "+%Y.%m.%d.%H.%M.%S")\n\n\n" >> $OutputLOG

apt-get install -y nload htop fuse p7zip-full >> $OutputLOG 2>&1

cd $SCLocation
wget https://downloads.rclone.org/rclone-current-linux-amd64.zip >> $OutputLOG 2>&1
unzip rclone-current-linux-amd64.zip >> $OutputLOG 2>&1
cd rclone-*-linux-amd64
cp rclone /usr/bin/
chown root:root /usr/bin/rclone
chmod 755 /usr/bin/rclone
mkdir -p /usr/local/share/man/man1
cp rclone.1 /usr/local/share/man/man1
mandb >> $OutputLOG 2>&1
cd ..
rm -f rclone-*-linux-amd64 rclone-current-linux-amd64.zip

cp "${local_packages}"/script/dalao/rcloned /etc/init.d/recloned
touch $LOCKLocation/rclone.lock
cd
